<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>Sign-Up/Login Form</title>
  <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,300,600' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

  
      <link rel="stylesheet" href="css/style.css">

  
</head>

<body>
    
  <div class="form">
      
      <ul class="tab-group">
        <li class="tab active"><a href="#signup">Sign Up</a></li>
        <li class="tab"><a href="#login">Log In</a></li>
      </ul>
      
      <div class="tab-content">
        <div id="signup">   
          <h1>Sign Up for Free</h1>
          
          <form  id="inscricao">
          
          <div class="top-row">
            <div class="field-wrap">
              <label>
                First Name<span class="req">*</span>
              </label>
              <input type="text" required autocomplete="off" name="nome" />
            </div>
        
            <div class="field-wrap">
              <label>
                Last Name<span class="req">*</span>
              </label>
              <input type="text"required autocomplete="off" name="lname" />
            </div>
          </div>

          <div class="field-wrap">
            <label>
              Email Address<span class="req">*</span>
            </label>
            <input type="text"required autocomplete="off" name="email" />
          </div>
          
          <div class="field-wrap">
            <label>
              Set A Password<span class="req">*</span>
            </label>
            <input type="password"required autocomplete="off" name="pass" />
          </div>
          
          <button type="button" onclick="inscricao()" class="button button-block"/>Get Started</button>
          
          </form>

        </div>


       
        <script type="text/javascript">
          function inscricao()
          {

            var nome  =  document.getElementById("inscricao").elements.namedItem("nome").value;
            var lname  =  document.getElementById("inscricao").elements.namedItem("lname").value;
            var email  =  document.getElementById("inscricao").elements.namedItem("email").value;
            var pass  =  document.getElementById("inscricao").elements.namedItem("pass").value;
            
            enviarUsuarioBanco(40,nome,lname,email,pass);

          }

        </script>
       
        <div id="login">   
          <h1>Welcome Back!</h1>
          
          <form id="loginUser"  method="post">
          
            <div class="field-wrap">
            <label>
              Email Address<span class="req">*</span>
            </label>
            <input name="email" type="text" />
          </div>
          
          <div class="field-wrap">
            <label>
              Password<span class="req">*</span>
            </label>
            <input name="senha" type="password"required autocomplete="off"/>
          </div>
          
          <p class="forgot"><a href="#">Forgot Password?</a></p>
          
          <button type="button" onclick="log()" class="button button-block"/>Log In</button>
          
          </form>

        </div>
        
      </div><!-- tab-content -->
      
</div> <!-- /form -->
  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

    <script src="js/index.js"></script>

<script src="https://www.gstatic.com/firebasejs/3.6.0/firebase.js"></script>
<script src="banco.js"></script>     

<script type="text/javascript">
  testeBanco();
</script>


</body>
</html>
