    <!DOCTYPE html>
<html>
  <head>
    <style type="text/css">
    html, body { height: 100%; margin: 0; padding: 0; }
   #map { height: 100%;width:100%}
    #tudo {
  width: 1000px;
  height: 600px;
}
#tudo1 {
  position:relative;
  width: 500px;
  height: 400px;
  background-color: green;
  float: left;
}
#tudo2 {
  position: relative;
  width: 500px;
  height: 400px;
  background-color: red;
  float: left;
}
    </style>
  </head>
  <body>

  <div id="tudo">
    <div id="tudo2">    
    </div>
    <div id="tudo1">
    <div id="map"></div>    
    </div>
    
  </div>
    
  <script type="text/javascript">
var map;
function initMap() {
 var myLatLng = {lat: -8.038148 , lng:  -34.871610};

  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 17,
    center: myLatLng
  });

  var marker = new google.maps.Marker({
    position: myLatLng,
    map: map,
    title: 'Hello World!'
  });
}

    </script>
    <script async defer
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA2Yc_Kc4Ajt-SviDucF4P-exF_XV57pZk&callback=initMap">
    </script>
  </body>
</html>