<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <title>Exemplo Calmon Ribeiro - Imasters</title>
        <style>
            .produtos{
                height: 200px;
                width: 250px;
                float: left;
                background-color: red;
                margin-right: 5px;
                margin-bottom: 5px;
            }
        </style>
    </head>
    <body>
        <div class="produtos"></div>
        <div class="produtos"></div>
        <div class="produtos"></div>
        <div class="produtos"></div>
        <div class="produtos"></div>
    </body>
</html>